import multer from 'multer';
import rateLimit from 'express-rate-limit';
import { Router } from 'express';
import { env } from '@/config/env.js';
import { addMembersController, archiveConversationController, attachmentController, blockedUsersController, blockUserController, chatUsersController, conversationController, conversationsController, createDirectConversationController, createGroupConversationController, deleteAttachmentController, deleteMessageController, editMessageController, forwardMessageController, markDeliveredController, markReadController, membersController, messageController, messagesController, muteConversationController, pinConversationController, removeMemberController, searchConversationsController, searchMessagesController, sendMessageController, unarchiveConversationController, unblockUserController, unmuteConversationController, unpinConversationController, updateConversationController, updateMemberController, uploadAttachmentsController, leaveConversationController } from '@/controllers/chat.controller.js';
import { addReactionController, announcementsController, bookmarksController, createAnnouncementController, createBookmarkController, createNoteController, deleteAnnouncementController, deleteBookmarkController, deleteNoteController, mentionsController, pinnedMessagesController, pinMessageController, removeReactionController, starMessageController, starredMessagesController, threadController, threadReplyController, unpinMessageController, unstarMessageController, updateAnnouncementController, updateNoteController, notesController } from '@/controllers/chat-collaboration.controller.js';
import { analyticsDashboardController, auditLogsController, conversationAnalyticsController, conversationTimelineController, createReportController, digestSettingsController, moderateReportController, reportsController, teamWorkspaceController, updateDigestSettingsController } from '@/controllers/chat-enterprise.controller.js';
import { authenticate } from '@/middleware/auth.js';
import { validateRequest } from '@/middleware/validate-request.js';
import { asyncHandler } from '@/utils/async-handler.js';
import { addMembersSchema, attachmentParamSchema, blockUserSchema, chatSearchQuerySchema, chatUserDirectoryQuerySchema, conversationParamSchema, conversationQuerySchema, conversationUpdateSchema, directConversationSchema, groupConversationSchema, messageCreateSchema, messageDeleteSchema, messageEditSchema, messageForwardSchema, messageParamSchema, messageQuerySchema, muteSchema, readReceiptSchema, updateMemberSchema, userParamSchema } from '@/services/chat/chat.validation.js';
import { announcementCreateSchema, announcementParamSchema, announcementUpdateSchema, bookmarkCreateSchema, bookmarkDeleteSchema, conversationQuerySchema as collaborationConversationQuerySchema, messageTargetSchema, noteCreateSchema, noteParamSchema, noteUpdateSchema, reactionSchema, threadQuerySchema, threadReplySchema } from '@/services/chat/chat.collaboration.validation.js';
import { auditQuerySchema, digestSettingsSchema, enterpriseConversationQuerySchema, moderationActionSchema, reportCreateSchema, reportParamSchema } from '@/services/chat/chat.enterprise.validation.js';

export const chatRouter = Router();

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: env.chatMaxDocumentSizeMb * 1024 * 1024, files: env.chatMaxAttachmentsPerMessage } });
const conversationLimiter = rateLimit({ windowMs: 60 * 60 * 1000, limit: env.chatConversationCreateLimitPerHour, standardHeaders: true, legacyHeaders: false });
const messageLimiter = rateLimit({ windowMs: 60 * 1000, limit: env.chatMessageRateLimitPerMinute, standardHeaders: true, legacyHeaders: false });
const searchLimiter = rateLimit({ windowMs: 60 * 1000, limit: env.chatSearchLimitPerMinute, standardHeaders: true, legacyHeaders: false });

chatRouter.use(authenticate);
chatRouter.get('/conversations', validateRequest({ query: conversationQuerySchema }), asyncHandler(conversationsController));
chatRouter.post('/conversations/direct', conversationLimiter, validateRequest({ body: directConversationSchema }), asyncHandler(createDirectConversationController));
chatRouter.post('/conversations/group', conversationLimiter, validateRequest({ body: groupConversationSchema }), asyncHandler(createGroupConversationController));
chatRouter.get('/users', searchLimiter, validateRequest({ query: chatUserDirectoryQuerySchema }), asyncHandler(chatUsersController));
chatRouter.get('/search/conversations', searchLimiter, validateRequest({ query: chatSearchQuerySchema }), asyncHandler(searchConversationsController));
chatRouter.get('/search/messages', searchLimiter, validateRequest({ query: chatSearchQuerySchema }), asyncHandler(searchMessagesController));
chatRouter.post('/reactions', messageLimiter, validateRequest({ body: reactionSchema }), asyncHandler(addReactionController));
chatRouter.delete('/reactions', messageLimiter, validateRequest({ body: messageTargetSchema }), asyncHandler(removeReactionController));
chatRouter.get('/mentions', validateRequest({ query: collaborationConversationQuerySchema }), asyncHandler(mentionsController));
chatRouter.get('/pins', validateRequest({ query: collaborationConversationQuerySchema }), asyncHandler(pinnedMessagesController));
chatRouter.post('/pins', validateRequest({ body: messageTargetSchema }), asyncHandler(pinMessageController));
chatRouter.delete('/pins', validateRequest({ body: messageTargetSchema }), asyncHandler(unpinMessageController));
chatRouter.get('/starred', validateRequest({ query: collaborationConversationQuerySchema }), asyncHandler(starredMessagesController));
chatRouter.post('/starred', validateRequest({ body: messageTargetSchema }), asyncHandler(starMessageController));
chatRouter.delete('/starred', validateRequest({ body: messageTargetSchema }), asyncHandler(unstarMessageController));
chatRouter.get('/threads', validateRequest({ query: threadQuerySchema }), asyncHandler(threadController));
chatRouter.post('/threads', messageLimiter, validateRequest({ body: threadReplySchema }), asyncHandler(threadReplyController));
chatRouter.get('/notes', validateRequest({ query: collaborationConversationQuerySchema }), asyncHandler(notesController));
chatRouter.post('/notes', validateRequest({ body: noteCreateSchema }), asyncHandler(createNoteController));
chatRouter.patch('/notes/:noteId', validateRequest({ params: noteParamSchema, body: noteUpdateSchema }), asyncHandler(updateNoteController));
chatRouter.delete('/notes/:noteId', validateRequest({ params: noteParamSchema }), asyncHandler(deleteNoteController));
chatRouter.get('/announcements', validateRequest({ query: collaborationConversationQuerySchema }), asyncHandler(announcementsController));
chatRouter.post('/announcements', validateRequest({ body: announcementCreateSchema }), asyncHandler(createAnnouncementController));
chatRouter.patch('/announcements/:announcementId', validateRequest({ params: announcementParamSchema, body: announcementUpdateSchema }), asyncHandler(updateAnnouncementController));
chatRouter.delete('/announcements/:announcementId', validateRequest({ params: announcementParamSchema }), asyncHandler(deleteAnnouncementController));
chatRouter.get('/bookmarks', validateRequest({ query: collaborationConversationQuerySchema }), asyncHandler(bookmarksController));
chatRouter.post('/bookmarks', validateRequest({ body: bookmarkCreateSchema }), asyncHandler(createBookmarkController));
chatRouter.delete('/bookmarks', validateRequest({ body: bookmarkDeleteSchema }), asyncHandler(deleteBookmarkController));
chatRouter.get('/workspace/:conversationId', validateRequest({ params: conversationParamSchema }), asyncHandler(teamWorkspaceController));
chatRouter.get('/timeline', validateRequest({ query: enterpriseConversationQuerySchema }), asyncHandler(conversationTimelineController));
chatRouter.get('/analytics', asyncHandler(analyticsDashboardController));
chatRouter.get('/analytics/:conversationId', validateRequest({ params: conversationParamSchema }), asyncHandler(conversationAnalyticsController));
chatRouter.post('/reports', validateRequest({ body: reportCreateSchema }), asyncHandler(createReportController));
chatRouter.get('/reports', validateRequest({ query: enterpriseConversationQuerySchema }), asyncHandler(reportsController));
chatRouter.patch('/reports/:reportId/moderation', validateRequest({ params: reportParamSchema, body: moderationActionSchema }), asyncHandler(moderateReportController));
chatRouter.get('/audit-logs', validateRequest({ query: auditQuerySchema }), asyncHandler(auditLogsController));
chatRouter.get('/notification-digest', asyncHandler(digestSettingsController));
chatRouter.patch('/notification-digest', validateRequest({ body: digestSettingsSchema }), asyncHandler(updateDigestSettingsController));
chatRouter.get('/blocked-users', asyncHandler(blockedUsersController));
chatRouter.post('/users/:userId/block', validateRequest({ params: userParamSchema, body: blockUserSchema }), asyncHandler(blockUserController));
chatRouter.post('/users/:userId/unblock', validateRequest({ params: userParamSchema }), asyncHandler(unblockUserController));
chatRouter.get('/attachments/:attachmentId', validateRequest({ params: attachmentParamSchema }), asyncHandler(attachmentController));
chatRouter.delete('/attachments/:attachmentId', validateRequest({ params: attachmentParamSchema }), asyncHandler(deleteAttachmentController));
chatRouter.get('/messages/:messageId', validateRequest({ params: messageParamSchema }), asyncHandler(messageController));
chatRouter.patch('/messages/:messageId', messageLimiter, validateRequest({ params: messageParamSchema, body: messageEditSchema }), asyncHandler(editMessageController));
chatRouter.delete('/messages/:messageId', messageLimiter, validateRequest({ params: messageParamSchema, body: messageDeleteSchema }), asyncHandler(deleteMessageController));
chatRouter.post('/messages/:messageId/forward', messageLimiter, validateRequest({ params: messageParamSchema, body: messageForwardSchema }), asyncHandler(forwardMessageController));
chatRouter.post('/messages/:messageId/delivered', validateRequest({ params: messageParamSchema }), asyncHandler(markDeliveredController));
chatRouter.get('/conversations/:conversationId', validateRequest({ params: conversationParamSchema }), asyncHandler(conversationController));
chatRouter.patch('/conversations/:conversationId', validateRequest({ params: conversationParamSchema, body: conversationUpdateSchema }), asyncHandler(updateConversationController));
chatRouter.post('/conversations/:conversationId/archive', validateRequest({ params: conversationParamSchema }), asyncHandler(archiveConversationController));
chatRouter.post('/conversations/:conversationId/unarchive', validateRequest({ params: conversationParamSchema }), asyncHandler(unarchiveConversationController));
chatRouter.post('/conversations/:conversationId/pin', validateRequest({ params: conversationParamSchema }), asyncHandler(pinConversationController));
chatRouter.post('/conversations/:conversationId/unpin', validateRequest({ params: conversationParamSchema }), asyncHandler(unpinConversationController));
chatRouter.post('/conversations/:conversationId/mute', validateRequest({ params: conversationParamSchema, body: muteSchema }), asyncHandler(muteConversationController));
chatRouter.post('/conversations/:conversationId/unmute', validateRequest({ params: conversationParamSchema }), asyncHandler(unmuteConversationController));
chatRouter.post('/conversations/:conversationId/leave', validateRequest({ params: conversationParamSchema }), asyncHandler(leaveConversationController));
chatRouter.delete('/conversations/:conversationId', validateRequest({ params: conversationParamSchema }), asyncHandler(leaveConversationController));
chatRouter.get('/conversations/:conversationId/members', validateRequest({ params: conversationParamSchema }), asyncHandler(membersController));
chatRouter.post('/conversations/:conversationId/members', validateRequest({ params: conversationParamSchema, body: addMembersSchema }), asyncHandler(addMembersController));
chatRouter.patch('/conversations/:conversationId/members/:userId', validateRequest({ params: conversationParamSchema.merge(userParamSchema), body: updateMemberSchema }), asyncHandler(updateMemberController));
chatRouter.delete('/conversations/:conversationId/members/:userId', validateRequest({ params: conversationParamSchema.merge(userParamSchema) }), asyncHandler(removeMemberController));
chatRouter.get('/conversations/:conversationId/messages', validateRequest({ params: conversationParamSchema, query: messageQuerySchema }), asyncHandler(messagesController));
chatRouter.post('/conversations/:conversationId/messages', messageLimiter, validateRequest({ params: conversationParamSchema, body: messageCreateSchema }), asyncHandler(sendMessageController));
chatRouter.post('/conversations/:conversationId/read', validateRequest({ params: conversationParamSchema, body: readReceiptSchema }), asyncHandler(markReadController));
chatRouter.post('/conversations/:conversationId/attachments', validateRequest({ params: conversationParamSchema }), upload.array('attachments'), asyncHandler(uploadAttachmentsController));
