import { Router } from 'express';
import { agreementRouter } from '@/routes/agreement.routes.js';
import { aiAssistantRouter } from '@/routes/ai-assistant.routes.js';
import { aiRouter } from '@/routes/ai.routes.js';
import { applicationRouter } from '@/routes/application.routes.js';
import { authRouter } from '@/routes/auth.routes.js';
import { diseaseRouter } from '@/routes/disease.routes.js';
import { farmJobRouter } from '@/routes/farm-job.routes.js';
import { farmCalendarRouter } from '@/routes/farm-calendar.routes.js';
import { farmManagementRouter } from '@/routes/farm-management.routes.js';
import { farmPlannerRouter } from '@/routes/farm-planner.routes.js';
import { healthRouter } from '@/routes/health.routes.js';
import { landRouter } from '@/routes/land.routes.js';
import { remoteMonitoringRouter } from '@/routes/remote-monitoring.routes.js';
import { weatherRouter } from '@/routes/weather.routes.js';
import { workerBookingRouter } from '@/routes/worker-booking.routes.js';
import { workerRouter } from '@/routes/worker.routes.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/applications', applicationRouter);
apiRouter.use('/agreements', agreementRouter);
apiRouter.use('/ai', aiRouter);
apiRouter.use('/assistant', aiAssistantRouter);
apiRouter.use('/disease', diseaseRouter);
apiRouter.use('/farm-jobs', farmJobRouter);
apiRouter.use('/farm-calendar', farmCalendarRouter);
apiRouter.use('/farm-management', farmManagementRouter);
apiRouter.use('/farm-planner', farmPlannerRouter);
apiRouter.use('/health', healthRouter);
apiRouter.use('/lands', landRouter);
apiRouter.use('/remote-monitoring', remoteMonitoringRouter);
apiRouter.use('/weather', weatherRouter);
apiRouter.use('/worker-bookings', workerBookingRouter);
apiRouter.use('/workers', workerRouter);
